"""Add extended student profile fields

Revision ID: 48406ecc149a
Revises: 19f987e49c5f
Create Date: 2025-10-04 22:42:58.050059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48406ecc149a'
down_revision: Union[str, Sequence[str], None] = '19f987e49c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first
    gender_enum = sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender')
    gender_enum.create(op.get_bind())
    
    parent_live_status_enum = sa.Enum('ALIVE', 'DECEASED', 'UNKNOWN', name='parentlivestatus')
    parent_live_status_enum.create(op.get_bind())
    
    applicant_type_enum = sa.Enum('STUDENT', 'PARENT', 'GUARDIAN', name='applicanttype')
    applicant_type_enum.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('students', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('parent_guardian_occupation', sa.String(), nullable=True))
    op.add_column('students', sa.Column('parent_guardian_monthly_income', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('parents_education_status', sa.String(), nullable=True))
    op.add_column('students', sa.Column('parent_live_status', parent_live_status_enum, nullable=True))
    op.add_column('students', sa.Column('scholarship_amount_requested', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('is_eligible_for_zakat', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('applicant_email', sa.String(), nullable=True))
    op.add_column('students', sa.Column('applicant_type', applicant_type_enum, nullable=True))
    op.add_column('students', sa.Column('applicant_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('applicant_mobile_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'applicant_mobile_number')
    op.drop_column('students', 'applicant_name')
    op.drop_column('students', 'applicant_type')
    op.drop_column('students', 'applicant_email')
    op.drop_column('students', 'is_eligible_for_zakat')
    op.drop_column('students', 'scholarship_amount_requested')
    op.drop_column('students', 'parent_live_status')
    op.drop_column('students', 'parents_education_status')
    op.drop_column('students', 'parent_guardian_monthly_income')
    op.drop_column('students', 'parent_guardian_occupation')
    op.drop_column('students', 'age')
    op.drop_column('students', 'gender')
    
    # Drop enum types
    sa.Enum(name='applicanttype').drop(op.get_bind())
    sa.Enum(name='parentlivestatus').drop(op.get_bind())
    sa.Enum(name='gender').drop(op.get_bind())
    # ### end Alembic commands ###
